// ReSharper disable InconsistentNaming
// <auto-generated />

namespace Contour.Testing.Plumbing
{
    public class MessagesReadyDetails
    {
        public double rate { get; set; }
    }

    public class MessagesUnacknowledgedDetails
    {
        public double rate { get; set; }
    }

    public class MessagesDetails
    {
        public double rate { get; set; }
    }

    public class PublishDetails
    {
        public double rate { get; set; }
    }

    public class ConfirmDetails
    {
        public double rate { get; set; }
    }

    public class ReturnUnroutableDetails
    {
        public double rate { get; set; }
    }

    public class GetDetails
    {
        public double rate { get; set; }
    }

    public class GetNoAckDetails
    {
        public double rate { get; set; }
    }

    public class DeliverDetails
    {
        public double rate { get; set; }
    }

    public class DeliverNoAckDetails
    {
        public double rate { get; set; }
    }

    public class RedeliverDetails
    {
        public double rate { get; set; }
    }

    public class AckDetails
    {
        public double rate { get; set; }
    }

    public class DeliverGetDetails
    {
        public double rate { get; set; }
    }

    public class MessageStats
    {
        public int publish { get; set; }
        public PublishDetails publish_details { get; set; }
        public int confirm { get; set; }
        public ConfirmDetails confirm_details { get; set; }
        public int return_unroutable { get; set; }
        public ReturnUnroutableDetails return_unroutable_details { get; set; }
        public int get { get; set; }
        public GetDetails get_details { get; set; }
        public int get_no_ack { get; set; }
        public GetNoAckDetails get_no_ack_details { get; set; }
        public int deliver { get; set; }
        public DeliverDetails deliver_details { get; set; }
        public int deliver_no_ack { get; set; }
        public DeliverNoAckDetails deliver_no_ack_details { get; set; }
        public int redeliver { get; set; }
        public RedeliverDetails redeliver_details { get; set; }
        public int ack { get; set; }
        public AckDetails ack_details { get; set; }
        public int deliver_get { get; set; }
        public DeliverGetDetails deliver_get_details { get; set; }
    }

    public class VirtualHost
    {
        public string name { get; set; }
        public bool tracing { get; set; }
        public int send_oct { get; set; }
        public SendOctDetails send_oct_details { get; set; }
        public int recv_oct { get; set; }
        public RecvOctDetails recv_oct_details { get; set; }
        public int messages_ready { get; set; }
        public MessagesReadyDetails messages_ready_details { get; set; }
        public int messages_unacknowledged { get; set; }
        public MessagesUnacknowledgedDetails messages_unacknowledged_details { get; set; }
        public int messages { get; set; }
        public MessagesDetails messages_details { get; set; }
        public MessageStats message_stats { get; set; }
    }
}
