// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Contour")]
[assembly: AssemblyProductAttribute("Contour")]
[assembly: AssemblyDescriptionAttribute("A library contains implementation of several EIP patterns to build the service bus.")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0")]
[assembly: AssemblyCopyrightAttribute("MIT License")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.0";
    }
}
